# Generated by Django 3.0.3 on 2020-02-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arts',
            options={'verbose_name_plural': 'Arts'},
        ),
    ]
